name: CI

on:
  push:
    branches:
      - main
  pull_request:
env:
  CI: true
  TEST: true

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.23.2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm build --filter ./packages
      - run: pnpm lint
      - run: pnpm check
  Tests:
    working-directory: packages/svemix
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install operating system dependencies
        run: npx playwright install-deps && npm install
      - name: Run your tests
        run: npm test

